# Generated by Django 5.2.5 on 2025-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United State'), ('FR', 'France'), ('GH', 'Ghana'), ('CM', 'Cameroon'), ('RU', 'Russia'), ('NG', 'Nigeria')], max_length=20),
        ),
    ]
