# Generated by Django 5.2.5 on 2025-08-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('CM', 'Cameroon'), ('US', 'United State'), ('GH', 'Ghana'), ('UK', 'United Kingdom'), ('RU', 'Russia'), ('NG', 'Nigeria'), ('FR', 'France')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Farmer', 'farmer'), ('Buyer', 'buyer')], max_length=7),
        ),
    ]
