# Generated by Django 5.2.5 on 2025-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_location_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('GH', 'Ghana'), ('CM', 'Cameroon'), ('NG', 'Nigeria'), ('US', 'United State'), ('FR', 'France'), ('UK', 'United Kingdom'), ('RU', 'Russia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Buyer', 'buyer'), ('Farmer', 'farmer')], max_length=7),
        ),
    ]
