# Generated by Django 4.2.18 on 2025-08-24 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_customuser_location_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('US', 'United State'), ('RU', 'Russia'), ('GH', 'Ghana'), ('FR', 'France'), ('CM', 'Cameroon'), ('UK', 'United Kingdom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Farmer', 'farmer'), ('Buyer', 'buyer')], max_length=7),
        ),
    ]
