# Generated by Django 4.2.18 on 2025-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_create_at_alter_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('CM', 'Cameroon'), ('FR', 'France'), ('GH', 'Ghana'), ('NG', 'Nigeria'), ('UK', 'United Kingdom'), ('RU', 'Russia'), ('US', 'United State')], max_length=20),
        ),
    ]
