# Generated by Django 4.2.18 on 2025-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('CM', 'Cameroon'), ('RU', 'Russia'), ('FR', 'France'), ('UK', 'United Kingdom'), ('US', 'United State'), ('GH', 'Ghana'), ('NG', 'Nigeria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Buyer', 'buyer'), ('Farmer', 'farmer')], max_length=7),
        ),
    ]
