# Generated by Django 4.2.18 on 2025-08-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customuser_location_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('US', 'United State'), ('NG', 'Nigeria'), ('UK', 'United Kingdom'), ('FR', 'France'), ('GH', 'Ghana'), ('CM', 'Cameroon'), ('RU', 'Russia')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Farmer', 'farmer'), ('Buyer', 'buyer')], max_length=7),
        ),
    ]
