# Generated by Django 4.2.18 on 2025-08-24 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customuser_location_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('GH', 'Ghana'), ('NG', 'Nigeria'), ('US', 'United State'), ('FR', 'France'), ('UK', 'United Kingdom'), ('CM', 'Cameroon'), ('RU', 'Russia')], max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_buyer', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
