# Generated by Django 4.2.18 on 2025-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_customuser_location_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('FR', 'France'), ('CM', 'Cameroon'), ('NG', 'Nigeria'), ('US', 'United State'), ('RU', 'Russia'), ('GH', 'Ghana'), ('UK', 'United Kingdom')], max_length=20),
        ),
    ]
