# Generated by Django 4.2.18 on 2025-08-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('CM', 'Cameroon'), ('FR', 'France'), ('NG', 'Nigeria'), ('RU', 'Russia'), ('GH', 'Ghana'), ('US', 'United State'), ('UK', 'United Kingdom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Buyer', 'buyer'), ('Farmer', 'farmer')], max_length=7),
        ),
    ]
