# Generated by Django 4.2.18 on 2025-08-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_customuser_location_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('US', 'United State'), ('NG', 'Nigeria'), ('UK', 'United Kingdom'), ('FR', 'France'), ('CM', 'Cameroon'), ('GH', 'Ghana'), ('RU', 'Russia')], max_length=20),
        ),
    ]
