# Generated by Django 4.2.18 on 2025-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('RU', 'Russia'), ('NG', 'Nigeria'), ('CM', 'Cameroon'), ('US', 'United State'), ('GH', 'Ghana'), ('FR', 'France'), ('UK', 'United Kingdom')], max_length=20),
        ),
    ]
