# Generated by Django 4.2.18 on 2025-08-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
