# Generated by Django 4.2.18 on 2025-08-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_request_updated_at_alter_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='buyers',
            new_name='buyer',
        ),
    ]
